name: "documentary"
author: "mssknd"
description: "check document maintenance"
branding:
  icon: "link"
  color: "green"
inputs:
  GITHUB_TOKEN:
    required: true
  target_branch:
    description: 'target branch name (default: origin/main)'
    default: 'origin/main'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: "check to maintain documents"
      shell: bash
      run: deno run -A https://deno.land/x/documentary/main.ts
    - name: "make comment on pull request when this action was pull request event."
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      shell: bash
      run: |
        echo "${{ inputs.target_branch }}"
        echo "${GITHUB_TOKEN}"
        echo "${URL}" |
        if ${{ github.event.pull_request.html_url }} = 'true'; then
          gh pr comment -F ./comments "${URL}"
        fi