name: "documentary"
author: "mssknd"
description: "check document maintenance"
branding:
  icon: "link"
  color: "green"
inputs:
  GITHUB_TOKEN:
    required: true
  base_branch:
    description: 'target branch name (default: main)'
    default: 'main'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Fetch base branch
      run: git fetch origin ${base_branch}:${base_branch}
    - name: "Check to maintain documents"
      id: check
      shell: bash
      # run: deno run -A https://deno.land/x/documentary/main.ts
      run: deno run -A main.ts -t ${base_branch} >> $GITHUB_OUTPUT
    - name: generate comment body file
      shell: bash
      env:
        PR_HEAD_SHA: ${{github.event.pull_request.head.sha}}
        PR_HEAD_FULL_NAME: ${{github.event.pull_request.head.repo.full_name}}
      run: deno run -A ./comment/main.ts -b ${PR_HEAD_FULL_NAME} -s ${PR_HEAD_SHA} -j '${{steps.check.outputs.json}}' >> comment-body
    - name: "make comment on pull request when this action was pull request event."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}      
      shell: bash
      run: |
        if [ -n "${PR_NUMBER}" ]; then
          gh pr comment ${PR_NUMBER} -F ./comment-body
        fi