name: documentaly-publish
author: MssKnd
description: Publish markdown to several platforms
branding:
  icon: file-text
  color: green
inputs:
  BASE_BRANCH:
    description: 'Base branch name (default: main)'
    default: main
  NOTION_API_TOKEN:
    description: Notion API token
  ZENDESK_API_AUTH_HEADER:
    description: 'Zendesk API auth header (ex. Authorization: <here>)'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: install documentaly
      shell: bash
      run: deno install -A --name documentaly https://deno.land/x/documentaly/mod.ts
    - name: Fetch base branch
      env: 
        BASE_BRANCH: ${{ inputs.BASE_BRANCH }}
      shell: bash
      run: git fetch origin ${BASE_BRANCH}
    - name: Check to publish documents
      env:
        NOTION_API_TOKEN: ${{ inputs.NOTION_API_TOKEN }}
        ZENDESK_API_AUTH_HEADER: ${{ inputs.ZENDESK_API_AUTH_HEADER }}
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash
      run: >
        documentaly publish
        $(gh pr diff ${PR_NUMBER} --name-only | grep '\.md$' | tr "\n" " "  )
        $([[ -n "${{ env.NOTION_API_TOKEN }}" ]] && echo "--notion-api-key ${{ env.NOTION_API_TOKEN }}" || echo "")
        $([[ -n "${{ env.ZENDESK_API_AUTH_HEADER }}" ]] && echo "--zendesk-api-auth-header ${{ env.ZENDESK_API_AUTH_HEADER }}" || echo "")
        > result.md
    - name: Check change files
      shell: bash
      run: |
        content=$(cat result.md)
        if [[ "$content" == "No change files." ]]; then
          echo "NO_CHANGE_FILES=true" >> $GITHUB_ENV
        else
          echo "NO_CHANGE_FILES=false" >> $GITHUB_ENV
        fi
    - name: Make comment on pull request when this action was pull request event.
      if: env.NO_CHANGE_FILES == 'false'
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: result.md
        comment_tag: documentaly-publish
