name: documentary
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  base_branch: main
jobs:
  check_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: documentary
        uses: mssknd/documentary@${{ github.event.pull_request.head.repo.full_name }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
