name: documentaly
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  BASE_BRANCH: main
jobs:
  check_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: documentaly
        uses: mssknd/documentaly@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
