name: documentary
on:
  pull_request:
    types: [synchronize]
jobs:
  documentary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: "test"
        shell: bash
        run: |
          ls -la
          git branch
      - name: "check to maintain documents"
        shell: bash
        # run: deno run -A https://deno.land/x/documentary/main.ts
        run: deno run -A main.ts
      - name: "make comment on pull request when this action was pull request event."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        shell: bash
        run: |
          echo "${GITHUB_TOKEN}"
          echo "${URL}" |
          if ${{ github.event.pull_request.html_url }} = 'true'; then
            gh pr comment -F ./comments "${URL}"
          fi
      # - name: documentary
      #   uses: mssknd/documentary@main
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # target_branch: main
