name: documentaly
on: pull_request
env:
  BASE_BRANCH: main
jobs:
  check_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: documentaly
        uses: mssknd/documentaly@feature/test-pass
        with:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
