name: documentaly-publish
on:
  pull_request
env:
  BASE_BRANCH: main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Use publish
        uses: ./actions/publish
        with:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
