name: documentaly-publish
on:
  pull_request:
    types: [closed]
env:
  BASE_BRANCH: main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: use documentaly-publish
        uses: mssknd/documentaly-publish@main
        with:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
