name: documentaly-publish
on:
  pull_request
env:
  BASE_BRANCH: main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: use documentaly-publish
        uses: ../../actions/publish
        with:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
