name: documentaly-publish
on: pull_request
  # pull_request:
  #   types: [closed]
env:
  BASE_BRANCH: main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use publish
        uses: mssknd/documentaly@feature/fix-comments:publish
        with:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
