name: publish

on: 
  pull_request #:
    # types: [closed]

env:
  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: install documentaly
        shell: bash
        run: deno install -A --name documentaly https://deno.land/x/documentaly/mod.ts
      - name: Fetch base branch
        shell: bash
        run: git fetch origin main
      - name: Check to publish documents
        env:
          NOTION_API_TOKEN: ${{ env.NOTION_API_TOKEN }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        shell: bash
        run: >
          documentaly publish
          $(gh pr diff ${PR_NUMBER} --name-only | grep '\.md$' | tr "\n" " "  )
          --notion-api-key ${{ env.NOTION_API_TOKEN }}
          >> result.md
      - name: Make comment on pull request when this action was pull request event.
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        shell: bash
        run: >
          if [ -n "${PR_NUMBER}" ]; then
            gh pr comment ${PR_NUMBER} -F ./result.md
          fi
      
