name: Test
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: documentary
        uses: mssknd/documentary@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
